version: '3.9'

services:
  app:
    image: evansdev/yamdb_final:latest
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:${PORT:-8000}
    stdin_open: true
    tty: true
    volumes:
      - static_volume:/home/app/dev/static
      - media_volume:/home/app/dev/media
    expose:
      - ${PORT:-8000}
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/dev/static
      - media_volume:/home/app/dev/media
    ports:
      - '80:80'
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
  media_volume:
