FROM python:3.9.6-alpine

WORKDIR /code/app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY ./requirements.txt .

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev openssl-dev graphviz-dev \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . .

RUN sed -i 's/\r$//g' ./entrypoint/dev.sh
RUN chmod +x ./entrypoint/dev.sh

ENTRYPOINT ["sh", "./entrypoint/dev.sh"]
